apiVersion: v1
kind: Service
metadata:
  name: svc-send-name
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 30000
  selector:
    app: send-name-app
